GET http://127.0.0.1:3000/api/v1/tasks

###

POST http://127.0.0.1:3000/api/v1/tasks
Content-Type: application/json

{
    "name":"to sleep"
}

###
GET http://127.0.0.1:3000/api/v1/tasks/64bd0bff7fac03bc4af79453


###

PATCH  http://127.0.0.1:3000/api/v1/tasks/64bd0bff7fac03bc4af79453
Content-Type: application/json

{
    "name":"to drink",
    "completed":true
}

###

DELETE   http://127.0.0.1:3000/api/v1/tasks/64bd0bff7fac03bc4af79453

